Getting application logs of containers
eclipse-kanto/container-management pull request #111
Opened 2022-12-20 12:37 UTC by k-gostev

[#98] Getting application logs of containers
- `kanto-cm logs` command is implemented according to the proposal in the issue

Signed-off-by: Kristiyan Gostev [kristiyan.gostev@bosch.io](mailto:kristiyan.gostev@bosch.io)

2023-01-03 14:01 UTC, antoniyatrifonova requested changes

2023-01-03 14:27 UTC, antoniyatrifonova approved these changes

2023-01-04 15:24 UTC, dimitar-dimitrow requested changes

2023-01-04 15:41 UTC, dimitar-dimitrow commented on containerm/services/grpc_containers_service.go
> +		if float64(len(buff.Bytes()))/(1<<20) > 3.5 {
Use variable for the maximum buffer size.

2023-01-05 08:25 UTC, dimitar-dimitrow commented on containerm/services/grpc_containers_service.go
> +		return path.Join(container.HostConfig.LogConfig.DriverConfig.RootDir, "json.log")
The DriverConfig type should be checked in order to use the correct file name. Currently there are json and none, but there might be more options in the future. Could you also check whether there is a constant for _json.log_?

2023-01-05 12:28 UTC, dimitar-dimitrow commented on containerm/cli/cli_command_ctrs_logs.go
> +	flagSet.Int32VarP(&cc.config.tail, "tail", "t", 100, "Lines of recent log file to display. Setting it to -1 will return all logs.")
We don't want the default behavior to be all logs, because the streaming and printing takes a lot of time and resources. It will remain as that.

2023-01-05 14:01 UTC, dimitar-dimitrow commented on containerm/services/grpc_containers_logs_util.go
> +		if !scanner.Scan() {
Scanner will return false on long lines and sending logs would terminate.

2023-01-05 14:44 UTC, dimitar-dimitrow commented on containerm/services/grpc_containers_logs_util.go
> +		logFileDir, _ := path.Split(container.HostsPath)
Use filepath instead of path.

2023-01-06 07:51 UTC, merged