Provide integration tests via the key Ditto features - Metrics
eclipse-kanto/container-management pull request #113
Opened 2023-01-05 14:37 UTC by antonia-avramova

[#71] Provide integration tests via the key Ditto features - Metrics

Signed-off-by: Antonia Avramova <antonia.avramova@bosch.io>

2023-01-06 07:59 UTC, k-gostev requested changes

2023-01-06 07:59 UTC, k-gostev commented on integration/ctr_metrics_test.go
> +// Copyright (c) 2022 Contributors to the Eclipse Foundation
```suggestion
// Copyright (c) 2023 Contributors to the Eclipse Foundation
```

2023-01-06 07:59 UTC, k-gostev commented on integration/ctr_metrics_test.go
> +}
please refactor it something like this:
```suggestion
				if !allowedPrefixID(mm.ID) {
					return true, fmt.Errorf("Invalid metrics ID: %s", mm.ID)
				}
			}
		}

		return len(expectedOriginators) == len(actualOriginators), nil
	})

	return result
}

func allowedPrefixID(id string) bool {
	allowedIDs := []string{"cpu.", "memory.", "io.", "net.", "pids"}
	for _, allowedID := range allowedIDs {
		if strings.HasPrefix(id, allowedID){
			return true
		}
	}
	return false
}
```

2023-01-06 08:00 UTC, k-gostev commented on integration/ctr_metrics_test.go
> +	params[paramImageRef] = "docker.io/library/httpd:latest"
`"docker.io/library/httpd:latest"` appears also [here](https://github.com/eclipse-kanto/container-management/blob/31ec917e881a090449e8aa61534a06acf18de217/integration/ctr_factory_test.go#L94). Please move it to `car_management_test_constants.go`

2023-01-09 09:58 UTC, antoniyatrifonova requested changes

2023-01-09 09:58 UTC, antoniyatrifonova commented on integration/ctr_metrics_test.go
> +)
You don't need this constants. You the value directly.

2023-01-13 12:49 UTC, k-gostev requested changes

2023-01-13 12:49 UTC, k-gostev commented on integration/ctr_metrics_test.go
> +	// "golang.org/x/net/websocket"
```suggestion
```

2023-01-13 12:49 UTC, k-gostev commented on integration/ctr_metrics_test.go
> +	params[paramFilter] = []things.Filter{filter}
Why do we need to redefine the frequency? Can't we use the `2s` interval defined above?

2023-01-13 12:49 UTC, k-gostev commented on integration/ctr_metrics_test.go
> +	filter.Originator = "test.process"
```suggestion
filter := things.Filter{Originator: "test.process"}
```

2023-01-13 12:49 UTC, k-gostev commented on integration/ctr_management_suite.go
> +	}()
Please create separate function for this to avoid duplication.

2023-01-16 15:27 UTC, antoniyatrifonova requested changes

2023-01-16 15:27 UTC, antoniyatrifonova commented on integration/ctr_metrics_test.go
> +	suite.assertContainerMetricsFeatures()
First assert the Metrics feature, before creating the containers. In the assertion verify that the definition of the feature is expected.

2023-01-16 15:27 UTC, antoniyatrifonova commented on integration/ctr_metrics_test.go
> +	suite.stopMetricsRequest()
In the `testMetrics` you stop the metric request. Also in this method the `stopMetricRequest` is invoked in defer function, that means this method call will be executed in any case. So there is no need to invoke the method again.

2023-01-16 15:27 UTC, antoniyatrifonova commented on integration/ctr_metrics_test.go
> +	filter.Originator = suite.firstCtrID
```suggestion
		filter := things.Filter{
		ID: []string{"cpu.*", "memory.*", "io.*", "net.*", "pids"},
		Originator: suite.firstCtrID,
	}

2023-01-16 15:27 UTC, antoniyatrifonova commented on integration/ctr_metrics_test.go
> +	_, err := util.SendDigitalTwinRequest(suite.Cfg, http.MethodGet, suite.metricsUrl, nil)
Assert for feature definition also.

2023-01-16 16:05 UTC, k-gostev commented on integration/ctr_factory_test.go
>  	defer func() {
```suggestion
defer suite.remove(ctrFeatureID)
```

2023-01-16 17:12 UTC, k-gostev requested changes
Just a couple of general suggestions.

2023-01-16 17:12 UTC, k-gostev commented on integration/ctr_metrics_test.go
> +	suite.executeMetrics(stopParams)
```suggestion
	suite.executeMetrics(map[string]interface{}{paramFrequency: "0s"})
```

2023-01-16 17:12 UTC, k-gostev commented on integration/ctr_metrics_test.go
> +	topicData := util.GetLiveMessageTopic(suite.ctrThingID, protocol.TopicAction(actionData))
I think those two variables are used only once in the `if` statements below. Could you check if we can just use the util functions there and avoid declaring them?

2023-01-18 13:35 UTC, antoniyatrifonova approved these changes

2023-01-19 10:11 UTC, k-gostev approved these changes

2023-01-19 14:13 UTC, dimitar-dimitrow requested changes

2023-01-19 14:13 UTC, dimitar-dimitrow commented on integration/ctr_metrics_test.go
> +	suite.secondCtrID = suite.create(ctrParams)
Those are actually the feature identifiers of the containers. first**CtrID** sounds like this is the identifier of the container and mislead me that the tests will fail as the metrics feature would not work with container id as an originator. Could you please change them to something like firstCtrFeatureID?

2023-01-19 15:08 UTC, dimitar-dimitrow approved these changes

2023-01-19 15:10 UTC, merged