[#63] Provided integration tests via the key Ditto features - Container per instance
eclipse-kanto/container-management pull request #123
Opened 2023-02-01 08:15 UTC by ognian-baruh

[#63] Provided integration tests via the key Ditto features - Container per instance
Covered operation of the container instance: start, stop, pause, resume, rename, remove, stopWithOptions, update

Signed-off-by: Ognian Baruh <Ognyan.Baruh@bosch.io>

2023-02-02 09:18 UTC, antoniyatrifonova requested changes

2023-02-02 09:18 UTC, antoniyatrifonova commented on integration/ctr_instance_test.go
> +	suite.executeWithExpectedSuccess(ctrFeatureID, "start", emptyParams)
Create a constant for operation names

2023-02-02 09:18 UTC, antoniyatrifonova commented on integration/ctr_instance_test.go
> +	suite.processStateChange(wsConnection, ctrFeatureID, "RUNNING")
Create a constant for container status. CREATED and RUNNING can be placed in ctr_management_test_constants.go file.

2023-02-02 09:18 UTC, antoniyatrifonova commented on integration/ctr_instance_test.go
> +func (suite *ctrInstanceSuite) TestStopContainer() {
Most lines in test methods are repeated. To prevent duplication create a new method that will be called in test methods

2023-02-02 10:45 UTC, k-gostev commented on integration/ctr_instance_test.go
> +}
```suggestion
func (suite *ctrInstanceSuite) createContainer(start boolean) string {
	params := map[string]interface{}{
		paramImageRef = influxdbImageRef,
		paramStart = start
	}
	return suite.create(params)
}

2023-02-10 13:04 UTC, antoniyatrifonova approved these changes

2023-02-10 14:08 UTC, antoniyatrifonova approved these changes

2023-02-10 14:31 UTC, k-gostev requested changes
A couple of nits:

2023-02-10 14:31 UTC, k-gostev commented on integration/ctr_instance_test.go
> +		if deletedCtrPath != event.Path {
```suggestion
		if event.Path != fmt.Sprintf("/features/%s", ctrFeatureID){
```

2023-02-10 14:31 UTC, k-gostev commented on integration/ctr_instance_test.go
> +			if statusUpdatePath != event.Path {
```suggestion
			if event.Path != fmt.Sprintf("/features/%s/properties/status/config", ctrFeatureID) {
```

2023-02-10 14:35 UTC, k-gostev commented
There is a lot of duplicate code that I would like to see avoided (for example 	`suite.executeWithExpectedSuccess(...)`
	and `suite.processStateChange(...)`  one ofter the other are used a lot, just with different parameters) . Please use [table driven approach](https://dave.cheney.net/2019/05/07/prefer-table-driven-tests). You can see examples in several places in this project as well. [One of the most recent examples](https://github.com/eclipse-kanto/container-management/blob/main/containerm/deployment/deployment_test.go)

2023-02-16 12:48 UTC, dimitar-dimitrow commented on integration/ctr_instance_test.go
> +		"test_stop_container_that_is_already_stopped": {
Actually the container is not stopped. It is in state created. Either change the test name to something like _stop_container_that_is_not_running_ or execute start->stop in advance.

2023-02-17 13:56 UTC, dimitar-dimitrow approved these changes

2023-02-17 14:37 UTC, k-gostev approved these changes

2023-02-20 08:07 UTC, antoniyatrifonova approved these changes

2023-02-20 08:16 UTC, merged