Provide integration test for the CLI list command
eclipse-kanto/container-management pull request #124
Opened 2023-02-02 08:07 UTC by antoniyatrifonova

[#117] Provide integration test for the CLI list command
- provide golden file
- provide yaml file with test scenarios

Signed-off-by: Guzgunova Antonia <Antonia.Guzgunova@bosch.io>

2023-02-02 10:31 UTC, k-gostev commented on integration/testdata/list-test.yaml
> +name: list_all_containers_with_same_name
Names are not the same in this test case (unfortunately there is no easy way currently that we can delete multiple containers with the same name from the CLI IT). I guess you can change this test case to assert multiple containers, different images as well.

2023-02-03 07:35 UTC, dimitar-dimitrow requested changes
Tests that list started and stopped containers could also be added in order to validate that correct statuses and exits codes are printed.

2023-02-03 07:35 UTC, dimitar-dimitrow commented on integration/testdata/list-test.yaml
> +name: list_all_containers
@antoniyatrifonova, could you please add one more container in this test? I want to cover the case where more than one conainer is listed.

2023-02-03 12:19 UTC, k-gostev approved these changes

2023-02-08 09:36 UTC, k-gostev approved these changes

2023-02-08 09:46 UTC, merged