Allow extra hosts entries to contain container mappings
eclipse-kanto/container-management pull request #128
Opened 2023-02-07 07:29 UTC by k-gostev

[#122] Allow the extra_hosts entries to contain other mappings

Signed-off-by: Kristiyan Gostev <kristiyan.gostev@bosch.com>

2023-02-08 08:02 UTC, dimitar-dimitrow requested changes

2023-02-09 07:25 UTC, k-gostev commented on containerm/mgr/mgr_internal.go
> +	containers := mgr.containersToArray()
all calls of `refreshAffectedContainers()` are called from methods that already locks the container resources. Calling it in `refreshAffectedContainers()` would create a deadlock.

2023-02-15 10:33 UTC, dimitar-dimitrow commented on integration/testdata/create-help.golden
> +                                     --hosts="container.service:container_service-host"
This will fail as the example is changed in the actual command flag description.

The same goes for the fixed type below **e**engine -> engine.

2023-02-15 10:33 UTC, dimitar-dimitrow commented on containerm/cli/cli_command_ctrs_create.go
> +		"If the IP of a container in the same bridge network is to be added to the contains hosts file the reserved container[_<container-host_name>] must be provided. Example:\n"+
**container[_<container-host_name>]** looks to me like the part in the square brackets is optional. It is this way for the host_ip example, but there is a default network interface that will be used. There is no default container host name to be used here, **container_<container-host_name>** is more accurate in my opinion.

Also could you please check the wording on this line, **contains** seems redundant.

2023-02-15 15:08 UTC, merged