[#165] Extend daemon configuration with settings for update agent
eclipse-kanto/container-management pull request #168
Opened 2023-06-15 13:53 UTC by stoyan-zoubev

Dummy implementation of Containers UpdateAgent implementation as Kanto container-management internal service.

- Added UpdateAgentConfig struct, flags and opts for internal containers UpdateAgent service.
- UpdateAgent not fully implemented, just the skeleton. Working implementation will follow with PRs.
- dependency to update-manager initial contribution branch, to be changed when PR for initial contribution is merged.

2023-07-05 10:06 UTC, dimitar-dimitrow requested changes

2023-07-05 10:06 UTC, dimitar-dimitrow commented on containerm/updateagent/update_operation.go
> +	}
This code is very repetitive, it might be moved to a separate method.

2023-07-06 06:14 UTC, stoyan-zoubev commented on containerm/updateagent/update_agent_init.go
> +	tlsConfig *tlsConfig) (api.UpdateAgent, error) {
Known issue, just added for completeness but currently it cannot be implemented.
It needs first support for TLS in UpdateManager/Agent APIs. A ticket is already open - https://github.com/eclipse-kanto/update-manager/issues/8.
After API is updated, TLS config will be used here too

2023-07-06 06:51 UTC, stoyan-zoubev commented on containerm/updateagent/update_agent_init.go
> +	domainName string, systemContainers []string, verboseContainers bool) api.UpdateManager {
renamed to verboseInventoryReport

2023-07-06 08:05 UTC, dimitar-dimitrow approved these changes

2023-07-06 08:22 UTC, k-gostev requested changes
A couple of nits, rest looks good

2023-07-06 08:22 UTC, k-gostev commented on containerm/daemon/daemon_internal.go
> +		if err != nil {
nit 
```suggestion
		if err := d.startUpdateAgents(); err != nil {
```

2023-07-06 08:22 UTC, k-gostev commented on containerm/daemon/daemon_internal.go
```suggestion
```

2023-07-06 08:44 UTC, stoyan-zoubev commented on containerm/daemon/daemon_internal.go
> +func (d *daemon) startUpdateAgents() error {
Currently we have only one update agent service anyway, so actually we do not have aggregation of errors. 
Initially, the code was without the for-iterations but these were by PR review request by @dimitar-dimitrow .
The implementation is similar to the already existing one for Things Manager. Either should change both functions or leave them as they are now.

2023-07-06 08:46 UTC, stoyan-zoubev commented on containerm/daemon/daemon_internal.go
> +		if err != nil {
Fixed also for Things Manager (old source code a few lines above).

2023-07-06 08:48 UTC, k-gostev approved these changes

2023-07-06 08:56 UTC, merged