Implement apply of desired state for containers update agent
eclipse-kanto/container-management pull request #174
Opened 2023-07-06 09:56 UTC by stoyan-zoubev

[#166] Implement apply of desired state for containers update agent

2023-07-07 08:51 UTC, dimitar-dimitrow requested changes

2023-07-07 08:51 UTC, dimitar-dimitrow commented on containerm/updateagent/to_containers.go
> +	}
This check could be moved to _util.ValidateContainer_ function.

2023-07-07 08:51 UTC, dimitar-dimitrow commented on containerm/updateagent/to_containers.go
> +func toContainer(component *types.ComponentWithConfig) (*ctrtypes.Container, error) {
This function is long and messy. Maybe it can be refactored in more easy to read way.

2023-07-07 08:51 UTC, dimitar-dimitrow commented on containerm/updateagent/to_containers.go
> +			NetworkMode: ctrtypes.NetworkModeBridge,
This should be filled by _util.FillDefaults_, if there is no value provided.

2023-07-07 08:51 UTC, dimitar-dimitrow commented on containerm/updateagent/to_containers.go
> +}
This code is duplicated in containerm/cli/cli_command_ctrs_create.go. Move the common code in the containerm/util packet and use it in both places.

2023-07-07 12:52 UTC, stoyan-zoubev commented on containerm/updateagent/to_containers.go
> +	}
Done with PR #175. The check here will be removed with next commit.

2023-07-07 12:53 UTC, stoyan-zoubev commented on containerm/updateagent/to_containers.go
> +}
Done with PR #175. The next commit will use containerm/util package.

2023-07-11 09:13 UTC, stoyan-zoubev commented on containerm/updateagent/to_containers.go
> +func toContainer(component *types.ComponentWithConfig) (*ctrtypes.Container, error) {
Refactored and simplified.

2023-07-11 10:40 UTC, stoyan-zoubev commented
Something went totally wrong with this PR and branches and rebasing/merging.
Closing this PR, replaced by a new one #177

2023-07-11 10:40 UTC, closed without merging