[#166] Preparation for implementing apply of containers desired state
eclipse-kanto/container-management pull request #175
Opened 2023-07-07 12:35 UTC by stoyan-zoubev

[#166] Preparation for implementing apply of desired state for containers update agent

Some preparation work before the real implementation:
- move parse functions from cli main package to common containerm/util package, to be used also by container update agent implementation, updated error messages to be more informative and show the problem
- added additional validation for container - cannot have a privileged container with specified devices

2023-07-10 06:23 UTC, dimitar-dimitrow requested changes
Unit test should written for the containers_parse.go

2023-07-10 06:23 UTC, dimitar-dimitrow commented on containerm/util/containers_validation.go
> +	if hostConfig.Privileged && len(hostConfig.Devices) > 0 {
Could you please add a test case for this validation check?

2023-07-10 06:23 UTC, dimitar-dimitrow commented on containerm/util/containers_parse.go
> +// Example: /dev/ttyACM0:/dev/ttyUSB0[:rwm].
Those go docs for the multiple and single container configurations parsing seems very repetitive. Maybe leave the format in the single functions and reference the single function in the multiple function go doc.

2023-07-10 11:46 UTC, stoyan-zoubev commented on containerm/util/containers_validation.go
> +	if hostConfig.Privileged && len(hostConfig.Devices) > 0 {
Validation check added with latest commit.

2023-07-10 15:13 UTC, stoyan-zoubev commented on containerm/util/containers_parse_test.go
> +	testCases := []struct {
I thought the valid input string was self-explainatory and enough. Anyway, test names added as map keys.

2023-07-11 06:56 UTC, k-gostev approved these changes

2023-07-11 06:58 UTC, merged