Implement apply of desired state for containers update agent
eclipse-kanto/container-management pull request #177
Opened 2023-07-11 10:39 UTC by stoyan-zoubev

[#166] Implement apply of desired state for containers update agent

Signed-off-by: Stoyan Zoubev Stoyan.Zoubev@bosch.io

2023-07-12 14:05 UTC, dimitar-dimitrow requested changes

2023-07-12 15:11 UTC, stoyan-zoubev commented on containerm/updateagent/update_operation.go
>  	if baselineAction == nil {
Nice catch! Refactored Execute function just to avoid such copy-paste mistakes.
Added baselineCommandHandler function type and correct command handler available in map[commandType].

2023-07-13 06:02 UTC, stoyan-zoubev commented on containerm/updateagent/to_containers.go
> +	container := &ctrtypes.Container{
Currently hostname and domainName are not available as input options for create CLI command, that's why these are not used here, when processing desired state for containers.
But the keys will be used when reporting the current state of the containers, especially when the verbose flag is true. So let's leave these keys as they are :)

2023-07-13 07:14 UTC, dimitar-dimitrow approved these changes

2023-07-13 07:47 UTC, k-gostev approved these changes

2023-07-13 07:48 UTC, merged