Add functionality to set different linux capabilities to a container.
eclipse-kanto/container-management pull request #178
Opened 2023-07-11 14:08 UTC by daniel-milchev

[#154] Add functionality to set different linux capabilities to a container.
Added the flag and updated the tests

Signed-off-by: Daniel Milchev fixed-term.daniel.milchev@bosch.io

2023-07-12 06:52 UTC, dimitar-dimitrow requested changes

2023-07-12 06:52 UTC, dimitar-dimitrow commented on containerm/cli/cli_commamd_ctrs_base_test.go
> +			err := val.Set(flagValue)
This change is not needed. The one line code seems to be clear enough. Maybe the change was used for some debugging purposes and got in the PR.

2023-07-12 06:52 UTC, dimitar-dimitrow commented on containerm/things/datatypes_container_configuration_test.go
>  	})
Those two sub-tests does not verify the output and expected length, there is no need for __len_ suffix in the sub-tests names.

2023-07-12 06:52 UTC, dimitar-dimitrow commented on containerm/util/containers.go
> +			ExtraCaps:   nil,
In go if you don't assign a value, a default value is used depending on the field type. E.g. int - 0, bool - false, string - "", []string - nil. There is no need to explicitly set the _ExtraCaps_ field to nil.

2023-07-12 07:01 UTC, stoyan-zoubev commented on containerm/cli/cli_command_ctrs_create.go
> +	if cc.config.privileged && cc.config.extraCaps != nil {
Shouldn't we also add similar check in the util.ValidateContainer function? 
@dimitar-dimitrow What do you think? Do you agree?

2023-07-12 07:06 UTC, dimitar-dimitrow commented on containerm/cli/cli_command_ctrs_create.go
> +	if cc.config.privileged && cc.config.extraCaps != nil {
Yes, well spotted!

2023-07-13 08:09 UTC, dimitar-dimitrow commented on containerm/util/protobuf/convert_to_proto_util.go
> +		ExtraCapabilities: internalHostConfig.ExtraCaps,
In one place it is the full form - _ExtraCapabilities_, on the other a short form is used _ExtraCaps_. Align them to be the same. My preferences are for the full form.

2023-07-13 08:47 UTC, k-gostev commented on containerm/cli/cli_command_ctrs_create.go
> +	if cc.config.privileged && cc.config.extraCaps != nil {
Im wondering if we should fail the creation of the container for this. Setting privileged will just apply all available capabilities to the container. The configuration is redundant and probably not desired by the user, but not fatal. Probably just a warning?

2023-07-13 08:54 UTC, k-gostev requested changes

2023-07-13 08:54 UTC, k-gostev commented on containerm/cli/cli_command_ctrs_create.go
> +	flagSet.StringSliceVar(&cc.config.extraCaps, "cap-add", nil, "Add capabilities to the container")
```suggestion
	flagSet.StringSliceVar(&cc.config.extraCaps, "cap-add", nil, "Add Linux capabilities to the container")
```

2023-07-13 08:54 UTC, k-gostev commented on containerm/util/containers_compare_test.go
> +		"test_hostconfig0_equal_capabilities": {
please consider creating some init function for the containers to avoid repetitions

2023-07-13 08:55 UTC, k-gostev commented
Integration tests should also be added.

2023-07-13 09:01 UTC, dimitar-dimitrow commented on containerm/cli/cli_command_ctrs_create.go
> +	if cc.config.privileged && cc.config.extraCaps != nil {
I am fine with just a warning, however shouldn't it be consistent with privileged set and device mapping provided? The privileged flag is taken with priority and all host devices are added with _rwm_ access.
Must be edited in the container_validation.go as well.

2023-08-07 12:18 UTC, k-gostev requested changes

2023-08-07 12:18 UTC, k-gostev commented on containerm/util/containers_compare_test.go
> +			current: setupContainerMounts([]types.MountPoint{{Destination: "testDestination1", Source: "testSource1", PropagationMode: "private"},
There is no point in this function as it does not save anything. As parameters add only what is changing and return the rest as default values. There is no need to pass the whole structures, just simplify the parameters as `string` arguments.

2023-08-07 12:18 UTC, k-gostev commented on containerm/util/containers_compare_test.go
> +			testutil.AssertEqual(t, testCase.expectedResult, res)
```suggestion
			testutil.AssertEqual(t, testCase.expectedResult, isEqualContainerConfig(testCase.current, testCase.desired))
```

2023-08-07 12:18 UTC, k-gostev commented on containerm/util/containers_compare_test.go
> +			testutil.AssertEqual(t, testCase.expectedResult, res)
```suggestion
			testutil.AssertEqual(t, testCase.expectedResult, isEqualHostConfig0(testCase.current, testCase.desired))
```

2023-08-08 08:24 UTC, k-gostev requested changes

2023-08-08 08:24 UTC, k-gostev commented on containerm/util/containers_compare_test.go
> +func setupContainerImage(name string) *types.Container {
```suggestion
func createContainerWithImage(name string) *types.Container {
```

2023-08-08 08:24 UTC, k-gostev commented on containerm/util/containers_compare_test.go
> +func setupContainerMounts(source string) *types.Container {
```suggestion
func createContainerWithMounts(source string) *types.Container {
```

2023-08-08 08:24 UTC, k-gostev commented on containerm/util/containers_compare_test.go
> +func setupContainerConfig(cmd []string) *types.Container {
```suggestion
func createContainerWithConfig(cmd []string) *types.Container {
```

2023-08-08 08:24 UTC, k-gostev commented on containerm/util/containers_compare_test.go
> +func setupContainerIOConfig(openstdin bool) *types.Container {
```suggestion
func createContainerWithIOConfig(openstdin bool) *types.Container {
```

2023-08-08 08:24 UTC, k-gostev commented on containerm/util/containers_compare_test.go
> +	defaultResPolicy := &types.RestartPolicy{
```suggestion
	defaultRestartPolicy := &types.RestartPolicy{
```

2023-08-08 08:24 UTC, k-gostev commented on containerm/util/containers_compare_test.go
> +	defaultDriverConf := &types.LogDriverConfiguration{
```suggestion
	defaultDriverConfig := &types.LogDriverConfiguration{
```
So it can be aligned with `DriverConfig`, `ModeConfig`, etc.

2023-08-08 08:24 UTC, k-gostev commented on containerm/util/containers_compare_test.go
> +	setIOConf := func(attachStderr, openstdin, tty bool) *types.IOConfig {
not sure about this, imo it makes the test more difficult to read, @dimitar-dimitrow wdyt?

2023-08-15 11:24 UTC, k-gostev commented on integration/ctr_management_cli_test.go
> +		if !strings.Contains(output, arg) {
This is not a proper way to assert JSON, either implement some more sophisticated approach that searches for the right key:value, or try with [jsonquery](https://github.com/antchfx/jsonquery).

2023-08-16 12:36 UTC, k-gostev approved these changes

2023-08-17 11:37 UTC, dimitar-dimitrow requested changes

2023-08-17 11:37 UTC, dimitar-dimitrow commented on containerm/util/containers_validation.go
> +}
```suggestion
// ValidatePrivileged validates that the container privileged configuration does not overlap with other configurations
func ValidatePrivileged(hostConfig *types.HostConfig) error {
	if hostConfig.Privileged {
		if hostConfig.Devices != nil {
			return log.NewError("cannot create the container as privileged and with specified devices at the same time - choose one of the options")
		}
		if hostConfig.ExtraCapabilities != nil {
			return log.NewError("cannot create the container as privileged and with extra capabilities at the same time - choose one of the options")
		}
	}
	return nil
}
```

2023-08-17 11:37 UTC, dimitar-dimitrow commented on containerm/cli/cli_command_ctrs_create.go
> +	if cc.config.privileged && cc.config.extraCaps != nil {
@daniel-milchev this is still not resolved, do we keep to the failing logic or change to warnings?

2023-08-17 11:37 UTC, dimitar-dimitrow commented on containerm/things/datatypes_container_configuration.go
> +	if !cfg.Privileged && cfg.ExtraCapabilities != nil && len(cfg.ExtraCapabilities) > 0 {
```suggestion
	if !cfg.Privileged && len(cfg.ExtraCapabilities) > 0 {
```

2023-08-17 11:37 UTC, dimitar-dimitrow commented on integration/ctr_management_cli_test.go
> +		}
This check and break is not needed.

2023-08-17 11:42 UTC, k-gostev commented on containerm/cli/cli_command_ctrs_create.go
> +	if cc.config.privileged && cc.config.extraCaps != nil {
I guess we can leave it like this to preserve the current behaviour and avoid confusion and ambiguity in the configuration.

2023-08-17 12:24 UTC, daniel-milchev commented on containerm/cli/cli_command_ctrs_create.go
> +	if cc.config.privileged && cc.config.extraCaps != nil {
> @daniel-milchev this is still not resolved, do we keep to the failing logic or change to warnings?

In my opinion it's simpler to just fail the creation of the container.

2023-08-17 13:41 UTC, dimitar-dimitrow approved these changes

2023-08-17 13:51 UTC, merged