Imporved unit tests.
eclipse-kanto/container-management pull request #203
Opened 2023-10-19 14:48 UTC by daniel-milchev

[#51] Imporved unit tests.
Signed-off-by: Daniel Milchev fixed-term.daniel.milchev@bosch.io

2023-10-24 07:11 UTC, dimitar-dimitrow requested changes

2023-10-24 07:11 UTC, dimitar-dimitrow commented on containerm/ctr/ctrd_container_create_opts_test.go
> +		execRoot  string
_image_ and _execRoot_ are always the same. Remove them from the test map and create variables and use them when invoking _WithSpecOpts_.

2023-10-24 07:11 UTC, dimitar-dimitrow commented on containerm/ctr/ctrd_container_create_opts_test.go
> +				},
Move in a separate sub-test the case where config is different from nil.

2023-10-24 07:11 UTC, dimitar-dimitrow commented on containerm/ctr/ctrd_container_create_opts_test.go
> +				},
```suggestion
```

2023-10-24 08:20 UTC, dimitar-dimitrow commented on containerm/ctr/ctrd_container_create_opts_test.go
> +	for name, tests := range tests {
```suggestion
	for name, test := range tests {
```

2023-10-25 07:14 UTC, k-gostev requested changes
I have not into much details, but this is what catch my eye at a glance

2023-10-25 07:14 UTC, k-gostev commented on containerm/ctr/ctrd_container_create_opts_test.go
> +// Copyright (c) 2021 Contributors to the Eclipse Foundation
![What year is it?](https://i.kym-cdn.com/entries/icons/original/000/007/784/what-year-is-it-robin-williams.jpg)

2023-10-25 07:14 UTC, k-gostev commented on containerm/ctr/ctrd_container_create_opts_test.go
> +	"github.com/containerd/containerd"
imports should be formatted in three groups:
```
import (
<system imports>

<current module libraries (*/eclipse-kanto/container-management/*)>

<other>
)

2023-10-25 07:14 UTC, k-gostev commented on containerm/ctr/ctrd_container_create_opts_test.go
> +			testutil.AssertNotNil(t, got)
`got` variable is not needed

2023-10-25 07:14 UTC, k-gostev commented on containerm/ctr/ctrd_client_test.go
> +			testutil.AssertError(t, expectedError, actualError)
this can be one line

2023-10-25 07:14 UTC, k-gostev commented on containerm/ctr/ctrd_client_test.go
> +				return log.NewErrorf("failed to initialise IO for container ID = test-id")
```suggestion
				return log.NewError("failed to initialise IO for container ID = test-id")
```

2023-10-25 13:25 UTC, k-gostev approved these changes

2023-10-26 08:38 UTC, dimitar-dimitrow approved these changes

2023-10-26 08:39 UTC, merged