Add file flag to the CLI create command
eclipse-kanto/container-management pull request #209
Opened 2023-11-07 16:01 UTC by daniel-milchev

[#208] Added the file flag. Added unit and integration tests for it.
Signed-off-by: Daniel Milchev [fixed-term.daniel.milchev@bosch.io](mailto:fixed-term.daniel.milchev@bosch.io)

2023-11-10 09:03 UTC, dimitar-dimitrow requested changes
As currently implemented one can use the `file` flag in combination with other flags. 
- If the same property(e.g. privileged) is defined through both it's flag and in the file, the property from the file is applied.
- If the property is defined only through it's flag and is missing in the file, then the flag gets applied.
This behavior is not intuitive, as usually flags have the highest priority. Applying the file as a base and then merging the configuration applied through flags is not straightforward and is prone to errors. As discussed with @k-gostev the best option is to forbid applying other flags when `file` is used.

2023-11-16 08:15 UTC, dimitar-dimitrow commented on containerm/cli/cli_command_ctrs_create.go
> +
```suggestion
	var (
		ctrToCreate *types.Container
		err error
	)
```

2023-11-16 08:26 UTC, dimitar-dimitrow approved these changes

2023-11-16 13:18 UTC, k-gostev approved these changes

2023-11-16 13:20 UTC, merged