Remove command should accept more than one container ID
eclipse-kanto/container-management pull request #212
Opened 2023-11-21 08:41 UTC by daniel-milchev

[#210] Changed remove command to accept more than one container.
Signed-off-by: Daniel Milchev fixed-term.daniel.milchev@bosch.io

2023-11-21 08:46 UTC, k-gostev requested changes
Unit and integration tests are missing

2023-11-21 13:20 UTC, dimitar-dimitrow commented on containerm/cli/cli_command_ctrs_remove.go
> +			cc.cli.gwManClient.Remove(ctx, ctr.ID, cc.config.force)
`Remove` could return an error, handle it.

2023-11-23 07:23 UTC, k-gostev approved these changes

2023-11-23 09:14 UTC, dimitar-dimitrow commented on containerm/cli/cli_command_ctrs_remove.go
>  		Long:  "Remove a container and frees the associated resources.",
```suggestion
		Use:   "remove <container-id> ...",
		Short: "Remove one or more containers.",
		Long:  "Remove one or more containers and frees the associated resources.",
```

2023-11-23 09:31 UTC, dimitar-dimitrow approved these changes

2023-11-23 09:35 UTC, merged