Filter and quiet flag for list CLI command.
eclipse-kanto/container-management pull request #221
Opened 2023-12-14 16:00 UTC by daniel-milchev

[#213] Added both flags and tests.
Signed-off-by: Daniel Milchev fixed-term.daniel.milchev@bosch.io

2023-12-18 08:36 UTC, k-gostev requested changes

2023-12-18 08:36 UTC, k-gostev commented on containerm/cli/cli_command_ctrs_list.go
> +	"strings"
```suggestion
	"strings"
```

2023-12-18 08:36 UTC, k-gostev commented on containerm/cli/cli_command_ctrs_list.go
> +		Example: " list\n list --name <container-name>\n list -n <container-name>\n list -q\n list --filter <status/image/exitcode>",
This is misleading. The `-q` example does not show an actual example, since the command format is `status=created` for example.

2023-12-18 08:36 UTC, k-gostev commented on containerm/cli/cli_command_ctrs_list.go
> +	flagSet.StringSliceVar(&cc.config.filter, "filter", nil, "Lists only containers with the filter.")
The `filter` flag must be explained better.

2023-12-18 08:36 UTC, k-gostev commented on containerm/cli/cli_command_ctrs_list.go
> +			convertedExitCode, err = strconv.Atoi(exitcodeHolder)
```suggestion
			convertedExitCode, err = strconv.Atoi(strings.TrimPrefix(inp, "exitcode="))
```

2023-12-18 08:36 UTC, k-gostev commented on integration/framework/cli/cmd_base.go
> +			// result := icmd.RunCmd(cmd.icmd)
```suggestion
```

2023-12-18 08:36 UTC, k-gostev commented on integration/framework/cli/cmd_base.go
> +			fmt.Printf("Running command: %s %s\n", cmd.icmd.Command[0], cmd.icmd.Command[1:])
```suggestion
```

2023-12-18 08:36 UTC, k-gostev commented on integration/framework/cli/cmd_base.go
> +		// icmd: *checkArguments(cmd.Command.Binary, cmd.Command.Args...),
```suggestion
```

2023-12-18 08:36 UTC, k-gostev commented on integration/framework/cli/cmd_base.go
> +		// cmds = append(cmds, *checkArguments(cmd.Binary, cmd.Args...))
```suggestion
```

2023-12-18 08:36 UTC, k-gostev commented on integration/testdata/list-test.yaml
> +name: list_containers_with_quiet
There are no tests with the filter flag

2023-12-18 14:46 UTC, dimitar-dimitrow requested changes

2023-12-18 14:46 UTC, dimitar-dimitrow commented on containerm/cli/cli_command_ctrs_list.go
> +	}
Executing `kanto-cm remove $(kanto-cm list --quiet)`, when there are no containers, results in:
```
Error: containers couldn't be removed due to the following reasons: 

* The requested container with ID = No was not found.
* The requested container with ID = found was not found.
* The requested container with ID = containers. was not found.
```

As quiet listing is supposed to work together with other kanto-cm commands, the preferred way is to have no output  and leave to the other command to pop up with an error - e.g. that no container id is provided.

```suggestion
	if cc.config.quiet {
		for i, ctr := range ctrs {
			if i != len(ctrs) - 1 {
				fmt.Printf("%s ", ctr.ID)
			} else {
				fmt.Println(ctr.ID)
			}
		}
		return nil
	}
```

2023-12-18 14:46 UTC, dimitar-dimitrow commented on containerm/cli/cli_command_ctrs_list.go
> +			return nil, fmt.Errorf("no such filter")
If there is more than one filters provided, it is unclear which one is incorrect.
```suggestion
			return nil, fmt.Errorf("no filter: %s", strings.Split(inp, "=")[0])
```

2023-12-19 14:20 UTC, dimitar-dimitrow commented on integration/testdata/list-test.yaml
> +    args: ["remove", "--host", "$KANTO_HOST", "-n", "list_containers_with_filter_two", "-f"]
Can't we use the remove with list quiet combo here?

2023-12-19 14:20 UTC, dimitar-dimitrow commented on containerm/cli/cli_command_ctrs_list.go
> +	flagSet.StringSliceVar(&cc.config.filter, "filter", nil, "Lists only containers with a specified filter. The containers can be filtered by their status, image and exitcode.")
Give example of a filtering.
```suggestion
	flagSet.StringSliceVar(&cc.config.filter, "filter", nil, "Lists only containers with a specified filter. The containers can be filtered by their status, image and exitcode. Example:\n--filter status=running")
```

2023-12-19 14:30 UTC, dimitar-dimitrow commented on containerm/cli/cli_command_ctrs_list.go
> +	flagSet.StringSliceVar(&cc.config.filter, "filter", nil, "Lists only containers with a specified filter. The containers can be filtered by their status, image and exitcode.")
Sorry, there is already an example above.

2023-12-20 08:26 UTC, dimitar-dimitrow approved these changes

2023-12-21 07:20 UTC, k-gostev approved these changes

2023-12-21 07:21 UTC, merged