CLI Remove command improvements
eclipse-kanto/container-management pull request #224
Opened 2024-01-08 15:02 UTC by daniel-milchev

[#217] CLI Remove command improvements
- Timeout was added to the remove command. 
- Timeout was changed in the stop command. 
- Changed default container stop timeout to duration string.

Signed-off-by: Daniel Milchev fixed-term.daniel.milchev@bosch.io

2024-01-09 15:34 UTC, dimitar-dimitrow requested changes

2024-01-09 15:34 UTC, dimitar-dimitrow commented on containerm/ctr/ctrd_client_test.go
>  				})
```suggestion
				mockReadCloser.EXPECT().Read(gomock.Any()).DoAndReturn(func(p []byte) (int, error) {
					return -1, io.EOF
				})..AnyTimes()
```
This is done in a separate  go routine and sometimes the test fails as it is not called on time. By adding AnyTimes those occasional fails would be eliminated.

2024-01-10 13:36 UTC, daniel-milchev commented on containerm/services/grpc_services_test.go
> +//TODO add tests for timeout
I don't think that a test is needed here. I wrote the comment but forgot to remove it before commiting.

2024-01-10 14:35 UTC, daniel-milchev commented on containerm/services/grpc_services_test.go
> +//TODO add tests for timeout
I added a test although it doesn't change the coverage of the code but it serves as a reminder in future development so the "StopOptions" aren't overlooked.

2024-01-11 15:38 UTC, dimitar-dimitrow requested changes

2024-01-12 10:03 UTC, dimitar-dimitrow approved these changes

2024-01-12 13:08 UTC, merged