Collect runtime metrics for containerized application
eclipse-kanto/container-management pull request #33
Opened 2022-07-11 09:10 UTC by dimitar-dimitrow

[#32] Implement collecting runtime metrics for containerized applications

Collects containers CPU, memory, IO, NET IO and PIDS stats from containerd and libnetwrk APIs.
Provides Metrics Ditto feature.

Signed-off-by: Dimitar Dimitrov <dimitar.dimitrov3@bosch.io>

2022-08-19 08:15 UTC, konstantina-gramatova commented
@dimitar-dimitrow The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).

This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances :blush: 

Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

2022-08-19 08:31 UTC, dimitar-dimitrow commented
> @dimitar-dimitrow The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).
> 
> This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances blush
> 
> Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

I understand and agree with the license change explained above.

2022-08-31 17:27 UTC, konstantina-gramatova requested changes

2022-08-31 17:27 UTC, konstantina-gramatova commented on containerm/things/features_metrics.go
> +			measurements = append(measurements, Measurement{ID: CPUUtilization, Value: util.CalculateCPUPercent(metrics.CPU, f.previousCPU[originator])})
What if the CPU percent is 0 here because we have not been able to calculate it? How will we differ between we have not been able to calculate it (i.e. it is not available) or it is actually 0 (e.g. the container has been paused)?

2022-08-31 17:27 UTC, konstantina-gramatova commented on containerm/containers/types/metrics.go
> +// CPUMetrics container stats regarding CPU.
Please, add a description that is a meaningful sentence here and in all the new API doc.

2022-09-01 11:12 UTC, dimitar-dimitrow commented on containerm/ctr/ctr_client_api.go
> +	GetContainerMetrics(ctx context.Context, container *types.Container) (*types.Metrics, error)
The whole instance is not needed, but I tried to keep the API consistent. It seems that the whole instance is provided to minimize future changes of the API, if anything else is needed except the ID. E.g. it is not needed as well in  DestroyContainer, Pause, Unpause and ReleaseContainerResources as well.

2022-09-01 11:12 UTC, dimitar-dimitrow commented on containerm/util/util_metrics.go
> +			aggregated.Softirq + aggregated.Steal)
I think it is right to calculated the usage x% from the whole CPU time, not from the time that the CPU has been busy. Same goes for memory usage it is calculated based on whole memory, not only the amount in use.

2022-09-01 11:12 UTC, dimitar-dimitrow commented on containerm/util/util_metrics.go
> +		usage := total * uint64(time.Second)
Yeah, TimeStats unit is seconds, we use nanoseconds.

2022-09-01 11:12 UTC, dimitar-dimitrow commented on containerm/network/net_mgr_api.go
> +	Metrics(ctx context.Context, container *types.Container) (*types.IOMetrics, error)
The whole instance is not needed, but I tried to keep the API consistent.

2022-09-01 14:09 UTC, konstantina-gramatova commented on containerm/util/util_metrics.go
> +		usage := total * uint64(time.Second)
Ok, as long as we are using `time.Second` only as a constant to convert with - gtg here : )

2022-09-09 14:44 UTC, konstantina-gramatova requested changes

2022-09-09 14:44 UTC, konstantina-gramatova commented on containerm/things/features_metrics.go
> +	}
Consider cleaning up the req field too here.

2022-09-10 06:00 UTC, dimitar-dimitrow commented on containerm/daemon/daemon_config_default.go
> +	thingsServiceFeaturesDefault = []string{things.ContainerFactoryFeatureID, things.SoftwareUpdatableFeatureID, things.MetricsFeatureID}
A separate issue is created - eclipse-kanto/kanto#121

2022-09-12 13:14 UTC, e-grigorov approved these changes

2022-09-12 13:16 UTC, konstantina-gramatova approved these changes

2022-09-12 13:18 UTC, merged