Provide integration tests via the key Ditto features - ContainerFactory
eclipse-kanto/container-management pull request #79
Opened 2022-10-18 15:38 UTC by antoniyatrifonova

[#70] Provide integration tests via the key Ditto features - ContainerFactory

- provide initial integration test setup for container-management components

Signed-off-by: Guzgunova Antonia <Antonia.Guzgunova@bosch.io>

2022-11-02 13:52 UTC, e-grigorov requested changes

2022-11-02 13:52 UTC, e-grigorov commented on integration/containerfactory_test.go
> +	require.Equal(suite.T(), ctrStateProp["status"], statusCreated, "The container state is not expected.")
`container state` - I guess that it's the status.

2022-11-02 13:52 UTC, e-grigorov commented on integration/request_util.go
> +	suite.doRequest(http.MethodPost, url, &requestBody{param: "true"})
General issue, the error cannot be ignored.

2022-11-09 09:36 UTC, e-grigorov commented on integration/common.go
> +func (suite *containerManagementSuite) newTestConnection() {
It seems that we are going in the right direction. The point is that, now, we have to connect and disconnect the suite i.e. suite.connect() and suite.disconnect(). Is it ok to connect the suite? Usually, we connect client, socket, device etc.

2022-11-09 09:36 UTC, e-grigorov commented on integration/common.go
> +	ns := model.NewNamespacedIDFrom(suite.containerID)
I guess that my previous comment wasn't clear enough. I would like to extend it. This variable is still the container identifier but the type is NamespacedID instead of string.

2022-11-09 09:36 UTC, e-grigorov commented on integration/containerfactory_test.go
> +	require.Equal(suite.T(), ctrStateProp["status"], statusCreated, "The container state is not expected.")
It seems that the issue is still there because of: `getActualCtrState`. It should be: `getActualCtrStatus` or I am missing something?

2022-11-09 09:36 UTC, e-grigorov commented on integration/request_util.go
> +	suite.doRequest(http.MethodPost, url, &requestBody{param: "true"})
The issue is still alive:
```
	if err != nil {
		suite.T().Logf("error while getting the container feature: %v", err)
	}
```
This snippet will just log. In case of an error, the test has to fail.

2022-11-10 10:43 UTC, e-grigorov commented on integration/request_util.go
> +	suite.doRequest(http.MethodPost, url, &requestBody{param: "true"})
Errrof will mark the test as failed and will continue. I am not sure, most probably, Fatalf has to be used which will interrupt the test execution. In any case, it can be aligned with the common/shared code reuse.

2022-11-15 13:35 UTC, hristobojilov approved these changes

2022-11-16 14:42 UTC, e-grigorov requested changes

2022-11-16 14:42 UTC, e-grigorov commented on integration/container_management_suite.go
> +type containerManagementSuite struct {
Currently, there are:
- ctrFactorySuite
- containerManagementSuite

In the end, what will be the `container` label/abbreviation? It should be unified to `ctr` or `container`.

2022-11-16 14:42 UTC, e-grigorov commented on integration/container_management_suite.go
> +	suiteInit            util.SuiteInitializer
Is there a real reason not to embed it? In the end, it has to be aligned with all other integration tests.

2022-11-16 14:42 UTC, e-grigorov commented on integration/container_management_suite.go
> +	edgeDeviceCfg, err := util.GetThingConfiguration(suite.suiteInit.Cfg, suite.suiteInit.MQTTClient)
`edgeDeviceCfg` should be `thingCfg`. In the end, it has to be unified with all other integration tests.

2022-11-16 14:42 UTC, e-grigorov commented on integration/container_management_suite.go
> +type containerFeature struct {
Actually, can we reuse something from the Ditto lib? I believe that we have similar/same structure there.

2022-11-16 14:42 UTC, e-grigorov commented on integration/container_management_suite.go
> +	suite.topicCreated = fmt.Sprintf("%s/%s/things/twin/events/created", ctrThingID.Namespace, ctrThingID.Name)
Actually, can we reuse something from the Ditto lib?

2022-11-16 15:14 UTC, e-grigorov commented on integration/container_factory_test.go
> +	for key := range features {
Is it safe to go through all containers? I guess that we should remove only the test containers. In this case, it's possible to test environment where some containers are already installed.

2022-11-16 15:16 UTC, e-grigorov commented on integration/container_factory_test.go
> +func (suite *ctrFactorySuite) TestCreateOperation() {
The name should be aligned with the suite connector. There, we have `TestCommand` i.e. command is used instead of operation.

2022-11-16 15:23 UTC, e-grigorov commented on integration/container_factory_test.go
> +			return false, fmt.Errorf("container feature is not created")
Do we need to stop the event processing in this case?

2022-11-16 15:26 UTC, e-grigorov commented on integration/container_factory_test.go
> +		return check && status["status"].(string) == statusRunning, nil
Do we need to ensure that `created` and `running` are in the right order as it's implemented on the topic level?

2022-11-16 15:28 UTC, e-grigorov commented on integration/container_factory_test.go
> +func (suite *ctrFactorySuite) TestCreateWithConfigOperation() {
Somehow duplicates `TestCreateOperation`. We can extract the common logic.

2022-11-16 15:31 UTC, e-grigorov commented on integration/container_factory_test.go
> +	body, err := util.SendDigitalTwinRequest(suite.suiteInit.Cfg, http.MethodGet, requestURL, nil)
SendDigitalTwinRequest cannot be used for any HTTP get request. It's Ditto specific.

2022-11-16 15:32 UTC, e-grigorov commented on integration/container_factory_test.go
> +	require.NoError(suite.T(), err, "error while getting the requested URL")
These two messages can be more concrete i.e. the context of the test container is missing.

2022-11-16 15:33 UTC, e-grigorov commented on integration/container_factory_test.go
> +	connEvents, err := util.NewDigitalTwinWSConnection(suite.suiteInit.Cfg)
It'll be nice to extract the common logic.

2022-11-21 13:39 UTC, e-grigorov requested changes

2022-11-21 13:39 UTC, e-grigorov commented on integration/container_factory_test.go
> +func (suite *ctrFactorySuite) TestCreateWithConfigCommand() {
Duplicates with TestCreateCommand.

2022-11-21 13:39 UTC, e-grigorov commented on integration/container_factory_test.go
> +	requestURL                  = "http://127.0.0.1:5000"
This request URL is specific for Apache HTTP server, it can be helpful to prefix it. For example, it can become: httpdRequestUrl

2022-11-21 13:39 UTC, e-grigorov commented on integration/container_factory_test.go
> +	httpResponse                = "<html><body><h1>It works!</h1></body></html>\n"
httpdResponse or something similar.

2022-11-21 13:39 UTC, e-grigorov commented on integration/container_factory_test.go
> +	require.NoError(suite.T(), err, "error while getting the container feature property status")
The error message can contain information about the feature identifier.

2022-11-21 13:39 UTC, e-grigorov commented on integration/container_factory_test.go
> +		if status["status"].(string) == statusCreated {
I guess that `check` has to be validated before the usage of `status`.

2022-11-21 13:39 UTC, e-grigorov commented on integration/container_factory_test.go
> +var isPropertyChanged bool
The property name is not completely correct. This field is set to true when the container is created. That's the essential point, `created` event.

2022-11-21 13:39 UTC, e-grigorov commented on integration/container_factory_test.go
> +func doRequest() ([]byte, error) {
`doRequest` is tool generic without arguments. Try to find a better name. It can be aligned with `requestURL` and `httpResponse` names i.e. put them in the context of Apache HTTP server.

2022-11-23 10:13 UTC, e-grigorov requested changes

2022-11-23 10:13 UTC, e-grigorov commented on integration/container_factory_test.go
> +func (suite *ctrFactorySuite) testCtrStatus(operation string, params interface{}) {
The status is not the main reason to have this method. That's the create operation.

2022-11-23 10:13 UTC, e-grigorov commented on integration/container_factory_test.go
> +func (suite *ctrFactorySuite) TestCreateCommand() {
`Command` suffix can be removed. Otherwise, `TestCreateWithConfigPortMapping` has to be aligned.

2022-11-23 12:11 UTC, hristobojilov requested changes

2022-11-24 09:10 UTC, e-grigorov commented on integration/container_factory_test.go
> +	connEvents, err := util.NewDigitalTwinWSConnection(suite.suiteInit.Cfg)
I still believe that this comment is valid. There is duplicated logic with testCtrCreated.

2022-11-24 09:21 UTC, e-grigorov commented on integration/container_factory_test.go
> +	return false, fmt.Errorf("container feature is not created")
It seems that this comment is still valid. This code is reachable in case of unknown message.

2022-11-24 09:21 UTC, e-grigorov commented on integration/container_factory_test.go
> +func doRequest() ([]byte, error) {
Still valid.

2022-11-24 12:07 UTC, e-grigorov requested changes

2022-11-24 12:07 UTC, e-grigorov commented on integration/container_factory_test.go
> +var isCtrFeatureCreated bool
Can be moved to the suite.

2022-11-24 12:07 UTC, e-grigorov commented on integration/container_factory_test.go
> +	require.NoError(suite.T(), err, "failed to reach the requested URL on host from the running container")
The error message is not correct. It's an WS message processing error.

2022-11-28 08:55 UTC, hristobojilov requested changes

2022-11-28 08:55 UTC, hristobojilov commented on integration/container_management_suite.go
> +	ctrFactoryDefinition := suite.ctrFactoryFeatureURL + "/definition"
Use GetFeaturePropertyValue if possible

2022-11-28 08:55 UTC, hristobojilov commented on integration/container_management_suite.go
> +	require.NoError(suite.T(), err, "failed to subscribe for the %s messages", typeEvents)
If this fails the connection will never be closed

2022-11-28 09:55 UTC, antoniyatrifonova commented on integration/container_management_suite.go
> +	ctrFactoryDefinition := suite.ctrFactoryFeatureURL + "/definition"
This is not the feature property.

2022-11-28 12:54 UTC, e-grigorov requested changes

2022-11-28 12:54 UTC, e-grigorov commented on integration/container_management_suite.go
> +	require.NoError(suite.T(), err, "event for creating the container feature is not received")
This is just one of the possible reasons for the error. I guess that the message has to be somehow more generic.

2022-11-28 12:54 UTC, e-grigorov commented on integration/container_management_suite.go
> +		return false, fmt.Errorf("unknown message received")
Do we need to stop on this error?

2022-11-28 12:54 UTC, e-grigorov commented on integration/container_management_suite.go
> +	defer closeWSConnection(wsConnection, err)
The defer arguments will be evaluated here. Next assigns of the variable will not be visible.

2022-11-28 12:54 UTC, e-grigorov commented on integration/container_management_suite.go
> +	require.NoError(suite.T(), err, "event for removing the container feature is not received")
or unknown message is received.

2022-11-28 12:54 UTC, e-grigorov commented on integration/container_factory_test.go
> +	require.NoError(suite.T(), err, "failed to create an HTTP request from the container")
`from` -> `to` - HTTP request to the container

2022-11-29 09:40 UTC, e-grigorov approved these changes

2022-11-29 13:06 UTC, hristobojilov approved these changes

2022-12-02 08:31 UTC, konstantina-gramatova requested changes

2022-12-02 08:31 UTC, konstantina-gramatova commented on integration/container_management_suite.go
> +	filter := fmt.Sprintf("like(resource:path,'/features/%s')", ctrFeatureID)
Better define `like(resource:path,'/features/%s` alongside all other constants.

2022-12-02 08:31 UTC, konstantina-gramatova commented on integration/container_management_suite.go
> +	httpdImageRef               = "docker.io/library/httpd:latest"
I would suggest to extract the common used constants _for the TCs_ (_not_ for the suite base) in a separate file (the marked ones, as well as ll such others below). In this container management suite base implementation only the ones that are relevant to it must be outlined here, otherwise in the future you risk to have this file as an ever-growing TCs consts dump.

2022-12-02 13:31 UTC, konstantina-gramatova requested changes
Please, revise all package constants and make sure to define such only if there's reusability in the package for them. Otherwise, define them only in the scope of the functions they are needed.

2022-12-02 13:31 UTC, konstantina-gramatova commented on integration/ctr_management_test_constants.go
> +)
Please, revise which of these really need to be package constants and which can be defined only in the scope of the functions they are used in - e.g. 



`operationRemove           = "remove"`

is used only for the `ctrManagementSuite.remove` func. Any extending structure (e.g. `ctrFactorySuite`) will need to "see"/use this function, not the constant.

2022-12-02 13:31 UTC, konstantina-gramatova commented on integration/ctr_factory_test.go
> +	config["portMappings"] = []map[string]interface{}{
There are constants defined for e.g. `paramStart` - shouldn't there be constants in this func defined for these keys as well?

2022-12-02 13:31 UTC, konstantina-gramatova commented on integration/ctr_management_suite.go
> +)
Please, revise which of these really need to be package constants and which can be defined only in the scope of the functions they are used in - e.g.

`filterCtrFeatures           = "like(resource:path,'/features/Container:*')"`

is used only for the` ctrManagementSuite.createWSConnection` func. Any extending structure (e.g. ctrFactorySuite) will need to use and "see"/use this function, not the constant.

2022-12-02 15:48 UTC, konstantina-gramatova requested changes

2022-12-02 15:48 UTC, konstantina-gramatova commented on integration/ctr_management_test_constants.go
> +
Add the missing integration build tag.

2022-12-02 15:48 UTC, konstantina-gramatova commented on integration/ctr_factory_test.go
> +	require.Equal(suite.T(), statusRunning, suite.getActualCtrStatus(ctrFeatureID), "container status is not expected")
This check is not needed as it is already asserted in the base `ctrManagementSuite.create` function.

2022-12-02 15:48 UTC, konstantina-gramatova commented on integration/ctr_management_test_constants.go
> +	statusRunning             = "RUNNING"
These values are needed only in the `ctrManagementSuite.create` function - please, relocate the declaration there.

2022-12-02 15:48 UTC, konstantina-gramatova commented on integration/ctr_management_suite.go
> +			}
This check must be made based on the `start` parameter value.

2022-12-02 15:48 UTC, konstantina-gramatova commented on integration/ctr_management_suite.go
> +func (suite *ctrManagementSuite) create(operation string, params interface{}) (*websocket.Conn, string) {
It will be quite handy to provide two wrapper functions here, e.g.:

`create` and `createWithConfig` that do not have an `operation` input parameter but call this implementation with the proper operation name internally. This way no package constants for the operations will be needed.

2022-12-02 15:48 UTC, konstantina-gramatova commented on integration/ctr_management_suite.go
> +				return true, fmt.Errorf("failed to parsing the property status value from the received event")
to parsing -> to parse

2022-12-02 15:48 UTC, konstantina-gramatova commented on integration/ctr_factory_test.go
> +func (suite *ctrFactorySuite) testCreate(operation string, params interface{}) {
This function should not be needed any more as the create logic will be wrapped with functions for the different operations.

2022-12-06 08:17 UTC, konstantina-gramatova requested changes

2022-12-06 08:17 UTC, konstantina-gramatova commented on integration/ctr_factory_test.go
> +	)
As of now, there are no reusability use cases for these constants neither in the scope of the T, nor out of it. Thus, for now it would be safe to have these values directly used as strings. In the future, if a reusabilyt use case comes up, the reusable ones can be defined in `ctr_management_test_constants.go` and used from there.

2022-12-06 08:17 UTC, konstantina-gramatova commented on integration/ctr_factory_test.go
> +	)
Same as the comment above.

2022-12-06 08:17 UTC, konstantina-gramatova commented on integration/ctr_management_suite.go
> +func getCtrFeatureID(topic string) string {
This function is intended to parse the feature ID from a Ditto path, not a topic. Please, fix the naming of the input parameter.

2022-12-06 08:17 UTC, konstantina-gramatova commented on integration/ctr_management_suite.go
> +	result := strings.Split(topic, "/")
Protect the code from an index out of range panic exit problems.

2022-12-06 08:17 UTC, konstantina-gramatova commented on integration/ctr_management_suite.go
> +func (suite *ctrManagementSuite) assertNoError(wsConnection *websocket.Conn, err error, message string, messageArs ...interface{}) {
Provide a meaningful name for this function - e.g. `closeOnError` or something like that.

2022-12-06 15:12 UTC, konstantina-gramatova requested changes

2022-12-06 15:12 UTC, konstantina-gramatova commented on integration/ctr_management_suite.go
> +			}
The value of the `status` property being `CREATED` does _not_ mean that the feature is created - this is asserted in the block lines 97-100. This property value means that the underlying container of the already created feature is in `CREATED` state. 

The current logic here will fail to assert the use case of a create operation executed with a `start` parameter equal to `false` - the listener will continue waiting for a second event endlessly even it has just received the needed `CREATED` one (line 111) .

The logic here can (and IMHO should) be really simplified to the following flow:
if status == created 
    if autostart -> mark container created and continue listening else -> stop listening
if status == running 
     if autostart and marked container created -> stop else -> stop error
stop error

2022-12-08 14:01 UTC, konstantina-gramatova requested changes

2022-12-08 14:01 UTC, konstantina-gramatova commented on integration/ctr_factory_test.go
> +	wsConnection, ctrFeatureID := suite.create(params)
What would happen with the `defer` statements if the create/createWithConfig execution has failed and the returned `ctrFeatureID` is actually ""? Do you think the remove operation will succeed both semantically and on Ditto level with a path containing `//`.

2022-12-09 08:24 UTC, antoniyatrifonova commented on integration/ctr_factory_test.go
> +	wsConnection, ctrFeatureID := suite.create(params)
> What would happen with the `defer` statements if the create/createWithConfig execution has failed and the returned `ctrFeatureID` is actually ""? Do you think the remove operation will succeed both semantically and on Ditto level with a path containing `//`.

Before execution of the removal operation, the client will be subscribed for the WS messages. For these messages, there is a filter that includes the container feature ID. If the container feature ID is "", the subscription process will fail as a result the remove operation will not be invoked.

2022-12-15 08:11 UTC, hristobojilov requested changes

2022-12-15 08:11 UTC, hristobojilov commented on integration/ctr_management_suite.go
> +func parseString(value interface{}) (string, error) {
This is a cast not parse operation.
You don't need to check if every cast is safe everywhere in the code. If unsafe cast fails the code will panic and the test will fail which is ok most of the time.

2022-12-16 13:32 UTC, konstantina-gramatova commented on integration/ctr_management_suite.go
> +func parseString(value interface{}) (string, error) {
I don't think it's a good idea to crash a TC with a an unhandled panic failure in general. Even more so when a part of the TC is actually to assert whether an expected payload is received or not.

2022-12-16 15:00 UTC, merged