[#8] MQTTS support in the container-management's local connection
eclipse-kanto/container-management pull request #80
Opened 2022-10-24 07:12 UTC by k-gostev

[#8] MQTTS support in the container-management's local connection

- parameter to set the CA used to sign the certificate of the local MQTT broker
- an optional device key and certificate, for the case when using device certificate is set as mandatory on the local MQTT broker

Signed-off-by: Kristiyan Gostev <kristiyan.gostev@bosch.io>

2022-10-31 08:30 UTC, konstantina-gramatova requested changes

2022-10-31 08:30 UTC, konstantina-gramatova commented on containerm/daemon/daemon_config.go
> +	Transport          tlsConfig `json:"transport,omitempty"`
Should be a pointer to the structure.

2022-10-31 08:30 UTC, konstantina-gramatova commented on containerm/things/things_containers_service_opts.go
> +func WithRootCA(rootCA string) ContainerThingsManagerOpt {
Think about whether the options should be handled in an atomic fashion as well - e.g. something like WithTLS.

2022-10-31 08:30 UTC, konstantina-gramatova commented on things/client/config/tls_config_test.go
> +	"github.com/eclipse-kanto/container-management/containerm/pkg/testutil"
The `github.com/eclipse-kanto/container-management/things` package must not import packages from `github.com/eclipse-kanto/container-management/containerm` - it should stay as independent as possible from the other packages in `github.com/eclipse-kanto/container-management/` as it is intended to be used as a standalone library by the other `github.com/eclipse-kanto/container-management/` packages or any other external ones.

The needed assertions here can be covered with the standard Go test SDK (e.g. `if->t.Fail/Fatal`) to avoid this import.

2022-10-31 08:30 UTC, konstantina-gramatova commented on things/client/client_config.go
> +func (cfg *Configuration) WithRootCA(rootCA string) *Configuration {
Consider an atomic TLS configuration here as well.

2022-10-31 08:30 UTC, konstantina-gramatova commented on things/client/config/tls_config.go
> +func NewLocalTLSConfig(rootCA, clientCert, clientKey string) (*tls.Config, error) {
If this logic is to become a part of the public API of the repo, then it should be made reusable in all the other components in it - e.g. the container image registries TLS handling to minimize the code duplication for these TLS use cases.

Consider extracting this TLS utility functions in a package e.g. `github.com/eclipse-kanto/container-management/util` and refactor the relevant code accordingly to use it.

2022-11-01 15:27 UTC, dimitar-dimitrow commented on util/tls/tls_config.go
> +	caCert, err := ioutil.ReadFile(caFile)
ioutul.ReadFile is deprecated, use os.ReadFile

2022-11-01 15:27 UTC, dimitar-dimitrow commented on util/tls/tls_config.go
> +	cfg := &tls.Config{
could directly return, no need of cfg variable

2022-11-01 15:27 UTC, dimitar-dimitrow commented on util/tls/tls_config.go
> +	cfg := &tls.Config{
could directly return, no need of cfg variable

2022-11-01 15:27 UTC, dimitar-dimitrow commented on util/tls/tls_config_test.go
> +package tls_test
throughout the project the test files share the same package name as the tested files

2022-11-01 15:27 UTC, dimitar-dimitrow commented on things/client/client_config.go
> +	tlsconfig "github.com/eclipse-kanto/container-management/util/tls"
the tlsconfig alias could be removed, this would lead to using tls.Config instead of the repetitive tlsconfig.Config

2022-11-01 15:27 UTC, dimitar-dimitrow commented on things/client/client.go
> +func setupLocalTLS(pahoOpts *MQTT.ClientOptions, configuration *Configuration) error {
the naming of setupLocalTLS is not appropriate as the broker could be a remote one, something like setupTLSConfiguration looks more suitable

2022-11-01 15:27 UTC, dimitar-dimitrow commented on util/tls/tls_config.go
> +// NewConfig initializes the Local broker TLS.
the broker could also be a remote one, also as it is moved to a separate utility 'broker' is out of context

2022-11-01 15:27 UTC, dimitar-dimitrow commented on containerm/things/things_test_base_test.go
> +	tlsconfig "github.com/eclipse-kanto/container-management/util/tls"
the tlsconfig alias could be removed, this would lead to using tls.Config instead of the repetitive tlsconfig.Config

2022-11-01 15:27 UTC, dimitar-dimitrow commented on containerm/things/things_containers_service_test.go
> +	tlsconfig "github.com/eclipse-kanto/container-management/util/tls"
the tlsconfig alias could be removed, this would lead to using tls.Config instead of the repetitive tlsconfig.Config

2022-11-01 15:27 UTC, dimitar-dimitrow commented on containerm/things/things_containers_service_opts.go
> +	tlsconfig "github.com/eclipse-kanto/container-management/util/tls"
the tlsconfig alias could be removed, this would lead to using tls.Config instead of the repetitive tlsconfig.Config

2022-11-01 15:27 UTC, dimitar-dimitrow commented on containerm/things/things_containers_service_init.go
> +	tlsconfig "github.com/eclipse-kanto/container-management/util/tls"
the tlsconfig alias could be removed, this would lead to using tls.Config instead of the repetitive tlsconfig.Config

2022-11-01 15:27 UTC, dimitar-dimitrow commented on containerm/daemon/daemon_config.go
> +	tlsconfig "github.com/eclipse-kanto/container-management/util/tls"
the tlsconfig alias could be removed, this would lead to using tls.Config instead of the repetitive tlsconfig.Config

2022-11-01 15:27 UTC, dimitar-dimitrow commented on util/tls/tls_config_test.go
> +	nonExisting = "nonexisting.test"
'nonExisting' could be moved to TestUseCertificateSettingsFail as it is only used there

2022-11-02 06:15 UTC, dimitar-dimitrow approved these changes

2022-11-07 08:35 UTC, konstantina-gramatova requested changes

2022-11-07 08:35 UTC, konstantina-gramatova commented on things/client/client_config.go
> +
This is a recursive call - please, fix it.
Also - the return type is not applicable.

2022-11-07 08:35 UTC, konstantina-gramatova commented on containerm/daemon/daemon_config.go
> +	Transport          tls.Config `json:"transport,omitempty"`
Must be a pointer to the TLS configuration.

2022-11-07 08:35 UTC, konstantina-gramatova commented on containerm/things/things_containers_service_opts.go
> +func WithTLSConfig(tlsConfig tls.Config) ContainerThingsManagerOpt {
The public API must be independent from any utilities.

2022-11-07 08:35 UTC, konstantina-gramatova commented on things/client/client_config.go
> +}
The public API must be independent from any utilities.

2022-11-07 08:35 UTC, konstantina-gramatova commented on util/tls/tls_config.go
> +}
Make sure this structure is really needed. The public APIs must not use it.

2022-11-07 08:35 UTC, konstantina-gramatova commented on util/tls/tls_config_test.go
> +	use, err := NewFSConfig(nil, "", "")
Please, add a meaningful name for the test and separate the cases inside - "OK" but the first case is testing an error state?

2022-11-07 08:35 UTC, konstantina-gramatova commented on util/tls/tls_config_test.go
> +	assertCertError(t, nonExisting, nonExisting, fmt.Errorf(expectedErrorStr, nonExisting))
The assertions are duplicated - any reason?

2022-11-29 13:43 UTC, konstantina-gramatova requested changes

2022-11-29 13:43 UTC, konstantina-gramatova commented on things/client/client_config.go
>  }
No need to have this as a public struct - the "getter" and "setter" should be aligned to a three-strings values.

2022-11-29 13:43 UTC, konstantina-gramatova commented on containerm/daemon/daemon_command.go
> +	flagSet.StringVar(&cfg.ThingsConfig.ThingsConnectionConfig.Transport.ClientKey, "things-conn-client-key", cfg.ThingsConfig.ThingsConnectionConfig.Transport.ClientKey, "Specify the PEM encoded unencr
Think about initializing the `cfg.ThingsConfig.ThingsConnectionConfig.Transport` field here IF it is not initialized up to this point rather than initializing it in the `getDefaultInstance()`.

2022-11-29 13:43 UTC, konstantina-gramatova commented on containerm/daemon/daemon_config_default.go
> +				Transport:          &tlsConfig{},
Check the comment in the [daemon_command.go](containerm/daemon/daemon_command.go) code.

2022-11-29 13:43 UTC, konstantina-gramatova commented on containerm/daemon/daemon_config_util.go
> +					log.Debug("[daemon_cfg][things-conn-client-key] : %d", configInstance.ThingsConfig.ThingsConnectionConfig.Transport.ClientKey)
Fix the `%d` formatting to `%s`.

2022-11-29 13:43 UTC, konstantina-gramatova commented on containerm/pkg/testutil/config/daemon-config.json
> +      "transport": {}
This should not be needed if the initialization of the transport is done while setting up the command flags.

2022-11-29 13:43 UTC, konstantina-gramatova commented on containerm/daemon/daemon_test.go
> +		},
I would also add a test like func TestThingsServiceFeaturesConfig that covers the Things Connection TLS configuration.

2022-12-02 11:01 UTC, konstantina-gramatova requested changes

2022-12-02 11:01 UTC, konstantina-gramatova commented on util/tls/tls_config_test.go
> +	assertCertError(t, "", "", fmt.Errorf(expectedErrorStr, ""))
Isn't this logic duplicate?

2022-12-05 13:51 UTC, konstantina-gramatova requested changes

2022-12-05 13:51 UTC, konstantina-gramatova commented on util/tls/tls_config.go
> +func newFSConfig(caCertPool *x509.CertPool, certFile, keyFile string) (*tls.Config, error) {
No need to provide the pool as an input here only to set it to a field of a returned structure. Simplify the purpose of this function - loading the client pair only.

2022-12-05 13:51 UTC, konstantina-gramatova commented on util/tls/tls_config.go
> +	if len(clientCert) > 0 || len(clientKey) > 0 {
This check can be done in the dedicated client pair loading function.

2022-12-05 13:51 UTC, konstantina-gramatova commented on util/tls/tls_config.go
> +	}, nil
Initialize the structure here only accordingly - based on the CA pool and loaded (if provided) client pair. Make sure we do not fallback into the case where the system pool is used - i.e. the RootCAs field is set to nil.

2022-12-05 13:51 UTC, konstantina-gramatova commented on util/tls/tls_config_test.go
> +}
Make sure to cover the error cases as well.

2022-12-05 13:51 UTC, konstantina-gramatova commented on util/tls/tls_config_test.go
> +	}
A test table could cover all these different use cases really well. Think about defining one.

2022-12-05 13:51 UTC, konstantina-gramatova commented on util/tls/tls_config_test.go
> +func testTLSConfig(t *testing.T, cfg *tls.Config) {
Isn't this function actually asserting a TLS config rather than testing it? Fix the naming accordingly.

2022-12-05 13:51 UTC, konstantina-gramatova commented on util/tls/tls_config.go
> +// newFSConfig initializes a file Hub TLS.
The doc/comment here is incorrect. Please, fix it. 

Also. please, think about a more explanatory/clear name of the helper function.

2022-12-05 14:23 UTC, k-gostev commented on util/tls/tls_config.go
> +	}, nil
RootCAs can't be nil since we always try to load a file from the provided `rootCA` parameter. Also, I would not initialize this structure only based on the CA pool and the key pair because according to the doc the MinVersion is defaulted to TLS 1.0 when used as as server and even though we are only using it as a client since its purpose there is to be a common library I don't want to leave that value as default.

2022-12-05 15:59 UTC, konstantina-gramatova commented on util/tls/tls_config.go
> +	}, nil
Sorry for the non-clear comment - I meant only the RootCAs and Certificates fields to be initialized with the results accordingly. Everything else is kept set explicit as it is now - `InsecureSkipVerify`, `MinVersion`, `MaxVersion`, `CipherSuites`.

2022-12-06 07:54 UTC, konstantina-gramatova commented on util/tls/tls_config_test.go
> +func assertInvalidTLSConfig(t *testing.T, caFile, certFile, keyFile string, expectedErr error) {
Do we need `assertInvalidTLSConfig` and `assertValidTLSConfig` as dedicated package functions given we have no reusability cases for them even in the scope of the TCs above?

2022-12-06 15:39 UTC, k-gostev commented on util/tls/tls_config_test.go
> +func assertInvalidTLSConfig(t *testing.T, caFile, certFile, keyFile string, expectedErr error) {
Good point, thanks. I don't even think we need to separate the valid from invalid config. IMO it would be better just to have all variants in the same test case map

2022-12-06 16:47 UTC, konstantina-gramatova requested changes

2022-12-06 16:47 UTC, konstantina-gramatova commented on util/tls/tls_config_test.go
> +)
Maybe now - having a single TC - we do not need these vars at package level? Could be constants in the scope of the TC?

2022-12-07 15:57 UTC, merged