[#69] Align the exposed confgurations per container via all remote APIs
eclipse-kanto/container-management pull request #82
Opened 2022-10-24 07:34 UTC by k-gostev

[#69] Align the exposed confgurations per container via all remote APIs

- Parameters for decryption configuration, network mode and host name are added

Signed-off-by: Kristiyan Gostev <kristiyan.gostev@bosch.io>

2022-10-26 08:11 UTC, konstantina-gramatova requested changes
The new versions of the used Vorto models have to be updated in their implementations in the stack where referenced as well.

2022-10-26 09:59 UTC, konstantina-gramatova requested changes

2022-10-26 09:59 UTC, konstantina-gramatova commented on containerm/things/datatypes_container_configuration.go
> +	DecryptConfig *decryptConfig `json:"decryptConfig,omitempty"`
The naming of the JSON fields must be compliant with the Vorto datatype definition - i.e. `decryption`.

2022-10-28 07:25 UTC, dimitar-dimitrow requested changes

2022-10-28 07:25 UTC, dimitar-dimitrow commented on containerm/things/datatypes_container_decryption_configuration.go
> +type decryption struct {
The naming of the type _decryption_ could be updated to _decryptionConfiguration_ to align with _logConfiguration_.
The names of this file and the corresponding test could also be aligned - _config_ instead _configuration_.

2022-10-28 07:25 UTC, dimitar-dimitrow commented on containerm/things/features_container_factory.go
> +	ctr.Image = types.Image{Name: imageRef, DecryptConfig: ctr.Image.DecryptConfig}
ctr.Image.Name could be directly set, instead of creating new Image structure.

2022-10-28 07:25 UTC, dimitar-dimitrow commented on containerm/things/datatypes_container_network_mode_test.go
> +		testutil.AssertEqual(t, bridge.toAPINetworkMode(), types.NetworkModeBridge)
The result from _toAPINetworkMode_ should be actual not the expected value.

2022-10-28 08:31 UTC, dimitar-dimitrow approved these changes

2022-10-31 07:45 UTC, konstantina-gramatova requested changes

2022-10-31 07:45 UTC, konstantina-gramatova commented on containerm/things/features_container_factory_test.go
> +		DecryptConfig: &types.DecryptConfig{},
This assignment overrides the DecryptConfig field value set during the initialization process of the `expectedCtr` variable on line 37:

```
expectedCtr = toAPIContainerConfig(testContainerConfig)
```
I would suggest here to only update the expected container image reference rather than overriding the whole Image struct, e.g. :

`expectedCtr.Image.Name = testContainerImage`

as it is kept in mind and considered in the new `*containerFactoryFeature.createWithConfig` implementation (line 171).

2022-10-31 09:49 UTC, konstantina-gramatova requested changes
Please, rebase the PR to main.

2022-10-31 09:49 UTC, konstantina-gramatova commented on containerm/things/datatypes_container_decryption_config_test.go
> +func TestFromAPIDecryptConfig(t *testing.T) {
Please, align the naming of all TCs with the new function names being tested, i.e.  `TestFrom/ToAPIDecryptionConfiguration`.

2022-10-31 10:36 UTC, konstantina-gramatova approved these changes

2022-10-31 10:39 UTC, merged