Add support for TCP protocol when using --host flag
eclipse-kanto/container-management pull request #85
Opened 2022-11-04 13:19 UTC by k-gostev

[#84] TCP Protocol is not supported by kanto-cm when using the --host flag

- `$ kanto-cm --host tcp://<host>:<port> <sub command>` no longer fails with error:
```log
"transport: Error while dialing dial unix tcp://<host>:<port> <sub command>: connect: no such file or directory"
```
- the behaviour to default to `unix` is still preserved

Signed-off-by: Kristiyan Gostev <kristiyan.gostev@bosch.io>

2022-11-21 13:33 UTC, dimitar-dimitrow commented on containerm/client/client_init.go
> +	ctx, cancel := context.WithTimeout(parentCtx, 30*time.Second)
I think it is a good idea to make the timeout configurable through global flag.

2022-11-29 13:33 UTC, konstantina-gramatova requested changes

2022-11-29 13:33 UTC, konstantina-gramatova commented on containerm/cli/cli_test.go
>  	testAddressPath = "test-address-path"
No reason to have  `testAddressPath`  defined as a const - rather define the value in the test struct in the test where it is used.

2022-11-29 13:33 UTC, konstantina-gramatova commented on containerm/client/client_init.go
> +	}
The case where an unsupported scheme is provided should be handled.

2022-11-29 15:15 UTC, konstantina-gramatova approved these changes

2022-11-29 15:16 UTC, merged