[#83] Expose flags --host and --debug to all child commands
eclipse-kanto/container-management pull request #86
Opened 2022-11-04 13:30 UTC by k-gostev

[#83] Flags --host and --debug should be global

- Flags `--host` and `--debug` are now inherited by all child commands of `kanto-cm`

- The flags can be seen when you list the help commands under `Global Flags`. Example:
```
$ kanto-cm list -h

List all containers.
...
Flags:
...
Global Flags:
      --debug         Switch commands log level to DEBUG mode
      --host string   Specify the address path to the Eclipse Kanto container management (default "/run/container-management/container-management.sock")
```

Signed-off-by: Kristiyan Gostev [kristiyan.gostev@bosch.io](mailto:kristiyan.gostev@bosch.io)

2022-11-15 15:39 UTC, konstantina-gramatova requested changes

2022-11-15 15:39 UTC, konstantina-gramatova commented on containerm/cli/cli_test.go
> +		debug:       false,
Please, use the defined constant here as well.

2022-11-15 15:39 UTC, konstantina-gramatova commented on containerm/cli/cli_test.go
> +	hostFlagName = "test-host"
Please, find a more suitable name for the variable (see the naming e.g. [here](https://github.com/eclipse-kanto/container-management/blob/29e76006abdf73ba487397eb073dad051c98e089/containerm/cli/cli_command_ctrs_update_test.go#L39)).

2022-11-18 09:04 UTC, dimitar-dimitrow commented on containerm/cli/cli_test.go
> +	debugCmdFlagName = "debug"
In the create command test there is _createCmdFlagName_ which is a constant for the name flag of the create command. So _hostCmdFlagName_ and _debugCmdFlagName_ sounds like there are host and debug commands with a name flag. Maybe naming them like _cmdFlagHost_ and _cmdFlagDebug_ would be more consistent.

2022-11-21 08:55 UTC, dimitar-dimitrow approved these changes

2022-11-29 09:11 UTC, konstantina-gramatova approved these changes

2022-11-29 09:12 UTC, merged