Implement signed images verification
eclipse-kanto/container-management pull request #94
Opened 2022-11-17 14:48 UTC by dimitar-dimitrow

[67] Implement signed images verification
- API for providing verification configuration per container
- container-management flag for providing global verification configuration
- verification manager API
- verification manager implementation based on cosign
- needed utility methods for parsing and validation
- needed modification to pass current unit test
- new dependencies are covered in NOTICE file

Signed-off-by: Dimitar Dimitrov <dimitar.dimitrov3@bosch.io>

2022-11-18 08:09 UTC, k-gostev reviewed
A couple of nits

2022-11-18 10:09 UTC, e-grigorov requested changes

2022-11-18 10:09 UTC, e-grigorov commented on containerm/ctr/ctr_verify_mgr.go
> +type containerVerifyMgr interface {
This interface requires some more work. It assumes that the signature is an image. There are get, pull and verify, I guess that some kind of encapsulation should be there.

2022-11-18 10:09 UTC, e-grigorov commented on containerm/daemon/daemon_config_util.go
> +		ctr.WithCtrdImageVerifyKeys(daemonConfig.ContainerClientConfig.CtrImageVerKeys...),
`ver` is more like a `version`. Is it possible to check and try another abbreviation, if it fits?

2022-11-21 15:38 UTC, dimitar-dimitrow commented on containerm/ctr/ctrd_client_internal.go
> +	}
The idea is that if there are no keys provided for verification, there is no need to pull the signature in first place. However this verify flag could be removed and the check could be performed once in the _verifyImage_ method. I would think whether the check in _VerifySignature_ is redundant and could be removed.

2022-11-21 15:42 UTC, dimitar-dimitrow commented on containerm/ctr/ctr_verify_mgr.go
> +type containerVerifyMgr interface {
The signature is an entity in a registry as per cosign and notary v2.  We could think of better solution, but we must keep downloading the signature and verifying as separate steps.

2022-11-30 08:52 UTC, k-gostev approved these changes
LGTM

2022-12-16 09:33 UTC, k-gostev requested changes

2022-12-16 09:33 UTC, k-gostev commented on containerm/ctr/ctrd_client_internal.go
>  	"time"
Please organise the imports

2022-12-16 09:33 UTC, k-gostev commented on containerm/ctr/ctrd_client_internal.go
> +var skipVerificationMessage = "signature verification is skipped for image = %s, %s"
```suggestion
const skipVerificationMessage = "signature verification is skipped for image = %s, %s"
Write
```
I think this can also be moved in the `verifyImage(...)` method if it is not used anywhere else.

2022-12-16 09:33 UTC, k-gostev commented on containerm/ctr/ctrd_client_internal.go
> +var signatureRegex = regexp.MustCompile(`-[a-f0-9]{64}.sig$`)
I think this can be moved in the `initImagesExpiryManagement(...)` method if it is not used anywhere else.

2022-12-16 09:33 UTC, k-gostev commented on containerm/ctr/ctrd_client_internal_test.go
>  	"syscall"
Please organise the imports

2022-12-16 09:33 UTC, k-gostev commented on containerm/ctr/ctrd_verification_mgr.go
> +)
Please organise the imports

2022-12-16 09:33 UTC, k-gostev commented on containerm/ctr/ctrd_verification_util.go
> +	"github.com/sigstore/sigstore/pkg/signature/payload"
Something like this:
```suggestion
	"encoding/base64"
 	"encoding/json"

 	"github.com/eclipse-kanto/container-management/containerm/log"
 	"github.com/eclipse-kanto/container-management/containerm/util"
 	errorUtil "github.com/eclipse-kanto/container-management/containerm/util/error"

 	ocispec "github.com/opencontainers/image-spec/specs-go/v1"
 	sig "github.com/sigstore/sigstore/pkg/signature"
 	"github.com/sigstore/sigstore/pkg/signature/payload"
 	"github.com/containerd/containerd/content"
 	"github.com/containerd/containerd/images"
 	"github.com/containerd/containerd/platforms"
```

2022-12-16 09:33 UTC, k-gostev commented on containerm/util/containers_validation.go
> +	"regexp"
```suggestion
	"regexp"

	"github.com/eclipse-kanto/container-management/containerm/containers/types"
	"github.com/eclipse-kanto/container-management/containerm/log"
```

2022-12-16 09:33 UTC, k-gostev commented on containerm/util/util_verification.go
> +	"strings"
Please organise the imports

2023-11-21 07:26 UTC, closed without merging